name: Peralal test build
on: push
jobs:
  addToCart-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:addToCart
      - name: Cypress Test Report            
        uses: actions/upload-artifact@v3
        with:
          name: Mocha HTML Report Add to Cart
          path: cypress/reports/html

  loginTest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:loginTest
      - name: Cypress Test Report            
        uses: actions/upload-artifact@v3
        with:
          name: Mocha HTML Report Login Test
          path: cypress/reports/html

  registerTest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:registerTest
      - name: Cypress Test Report            
        uses: actions/upload-artifact@v3
        with:
          name: Mocha HTML Report Register Test
          path: cypress/reports/html

  searchTest-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:searchTest
      - name: Cypress Test Report            
        uses: actions/upload-artifact@v3
        with:
          name: Mocha HTML Report Search Test
          path: cypress/reports/html





          
            